name: Without-ci-only-cd pipieline
on:
  registry_package:
    types: [published]

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v3

      - name: Update YAML
        run: |
          sed -i 's|image: .*|image: ghcr.io/anubhavbss/without-cd:latest|' new-deploy.yaml

      - name: Commit
        run: |
          git commit -am "Update image"
          git push




   
